version: '3.8'

services:
  sagard-postgres:
    image: postgres:16-alpine
    container_name: sagard-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: sagard_db
      POSTGRES_USER: sagard
      POSTGRES_PASSWORD: sagard_prod_Xk9m2024!
    volumes:
      - sagard_pgdata:/var/lib/postgresql/data
    ports:
      - '127.0.0.1:5435:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U sagard -d sagard_db']
      interval: 10s
      timeout: 5s
      retries: 5

  sagard-redis:
    image: redis:7-alpine
    container_name: sagard-redis
    restart: unless-stopped
    command: redis-server --requirepass sagard_redis_prod_2024
    ports:
      - '127.0.0.1:6381:6379'
    volumes:
      - sagard_redis:/data

volumes:
  sagard_pgdata:
  sagard_redis:
